---
title: Itinerary for Visit to Calvin
subtitle: Joseph Cho and Hanjin Lee, Handong University
date: last-modified
format:
  html: default
  typst: 
    margin:
      x: 0.7in
      y: 0.7in
    fontsize: 11pt

---



# Draft Schedule 

Some notes about the schedule:

1. This is a draft and subject to change. In particular, we 
are waiting for some input from Joseph Cho and Hanjin Lee about 
their preferences.

2. Items in *italics* are options we can decide about.

3. Items that are ~~struck through~~ are also options, but I'm assuming they won't happen unless I get feedback to the contrary.

4. Items in **bold** are planned, but they can be removed 
or adjusted as desired.


## Friday, February 13

* Joseph Arrives at GRR (late evening), transport to Prince CC
    * Soyeaon Chun will pick up at airport

## Saturday, February 14

* Hanjin arrives at GRR (22:47), transport to Prince CC
    * Delta Air Lines DL1711 from St Paul (MSP) 20:20 
      to Grand Rapids (GRR) 22:47
    * Matt Lundberg will pick up at airport

* Joseph and his wife spend day with Soyeon Chun

* Note: RJP is likely not available most of Saturday

## Sunday, February 15

* church attendance and lunch with Soyeon Chun

* Dinenr: TBD (RJP is available)

* Note: RJP has church obligations 8 - 12:30

## Monday, February 16

 <!-- Time --> | <!-- Activity --> 
:-------------:|:-------------------------------
 08:00 - 09:00 | **Breakfast at Prince CC**
 09:15 - 10:20 | *~~Visit PHIL 205 (Ethics)~~*
 10:30 - 10:50 | *~~Chapel: Sounds of South Asian Worship~~*
 11:00 - 12:05 | *~~Stat 145 (Intro Biostats)~~* 
 12:15 - 13:20 | **Lunch** in dining hall with Deb Haarsma (director of INCHE) and Derek Schuurman
 13:30 - 14:35 | **Norms for DS, Stat and Math?** (Fernando Santos)       
 14:45 - 15:50 | **open**; *conversation with Derek Schuurman?*
 16:00 - 17:30 | *Meeter Center Lecture: Dutch/Christianity in Indonesia*
 17:30 - 19:00 | **Dinner** with Thomas Scofield and Stacy DeRuiter
: {tbl-colwidths="[20,80]"}


## Tuesday, February 17

 <!-- Time --> | <!-- Activity --> 
:-------------:|:-------------------------------
 08:00 - 09:40 | Breakfast at Prince CC         
 10:20 - 12:00 | DeVries Post-docs (underprepared student groups) <br> or CS 384 (Perspectives) <br> leave early for **lunch** in dining hall with Fernando Santos
 12:15 - 13:55 | **Visit Stat 245 (Appl. Data Analysis)** <br> ~~or CS 384 (Perspectives)~~
 14:05 - 15:00 | 2:00 **Meet President Elzinga**, then open/seminar prep
 15:05 - 15:50 | **CS Seminar: Hanjin Lee**<br>*Values and Ethics in Mathematics in the age of AI*
 17:00 - 18:30 | **Dinner** with Derek Schuurman and Stacy DeRuiter 
 19:00 - 22:00 | [*Banff Film Festival Screening*](https://calvin.edu/academics/school-stem/geo/events/banff)
: {tbl-colwidths="[20,80]"}

## Wednesday, February 18

 <!-- Time --> | <!-- Activity --> 
:-------------:|:-------------------------------
 08:00 - 09:00 | Breakfast at Prince CC         
 09:15 - 10:20 | **Visit PHIL 205 (Ethics)**
 10:30 - 10:50 | *~~Chapel: Why Believe that Jesus Suffered?~~*
 11:30 - 12:05 | **lunch** with Kevin Timpe (Philosophy) and Derek Schuurman
 12:15 - 13:20 | **open**
 13:30 - 14:35 | **Faith and Learning Cohort: Heidelberg Catehchism and Faith Integration**
 14:45 - 15:50 |     
 16:00 - 17:00 | **Faculty Seminar: Hanjin Lee** <br>*Ethics in Mathematics: how to teach it at Christian Universities?* <br>As AI advances, the social practice of mathematics faces new ethical challenges. While more math and statistics students are entering the Big Data and AI sectors, they receive little ethical guidance in their formal education. Compared to the established professional ethics courses in engineering and science, mathematics and statistics departments lack similar curricula. This talk explores the ethical dimensions of mathematics and recent scholarly proposals. I will also propose a course design for ethics in mathematics based on a Christian narrative ethics framework.
 17:00 - 19:00 | **Dinner** with members of Math/Stat/CS departments (Vos Endowment)
: {tbl-colwidths="[20,80]"}


## Thursday, February 19

 <!-- Time --> | <!-- Activity --> 
:-------------:|:-------------------------------
 08:00 - 09:00 | Breakfast at Prince CC 
 09:30 - 10:15 | **Discussion about Calculus Revisions** (Jocye Chew, Todd Kapitula, Mike Bolt)
 10:20 - 12:00 | Visit **CS 384 (Prespectives)** <br> leave early for **lunch in dining hall** with Stacy DeRuiter
 12:15 - 13:55 | **Stat 245: Jim VanderMey** <br>*Making the Invisible Visible: Ethics, Systems, and the Future We’re Building* <br>In a world increasingly shaped by data, design, and automation, the deepest ethical decisions are often the ones we never see — embedded in architecture, algorithms, and assumptions. In this keynote, Jim VanderMey draws on decades of real-world practice as a technologist and his formation in theology to explore how we can surface these hidden choices, provide ethical leadership in a pluralistic society, and anticipate the long-term consequences of what we build — before they are felt.
 14:10 - 15:00 | **Informal discussion with Jim VanderMey** (with refreshments)<br> prep for colloquium
 15:05 - 15:50 | **Math/Stat Colloquium: Joseph Cho** <br> [*Geometry: Mathematics You Can See*](https://calvin-mathematics-colloquium.netlify.app/announcements/announcement-2026-02-19)
 17:00 - 18:30 | **Dinner** with Jim VanderMey, Dave Klanderman, Randy Pruim, Chris Moseley
: {tbl-colwidths="[20,80]"}


## Friday, February 20

 <!-- Time --> | <!-- Activity --> 
:-------------:|:-------------------------------
 08:00 - 09:00 | **Breakfast** at Prince CC         
 09:15 - 10:20 | 
 10:30 - 10:50 | **Chapel**
 11:00 - 12:05 | 
 12:15 - 13:20 | **lunch** with Thomas Scofield and John Ferdinands  
 13:30 - 14:35 |        
 14:45 - 15:50 | **Debrief and Discussion about trip to Korea**    
 17:30 - 19:00 | **Dinner** with Sung Soo Lim
: {tbl-colwidths="[20,80]"}

## Saturday, February 21

* Excursion in Grand Rapids area
    * Grand Rapids Art Museum?
    * Frederik Meijer Gardens?

* Lunch:
* Dinner:

## Sunday, February 22

* Departure from GRR @ 8am
    * Endeavor air DBA DELTA DL5180
      from GRR 08:00 am to DTW (Detroit) 